image:
  - Visual Studio 2019
  - Ubuntu
  - macOS

platform:
  - x86
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 3.5
      PYTHON_BUILD: ''
    - PYTHON_VERSION: 3.5
      PYTHON_BUILD: '-x64'
    - PYTHON_VERSION: 3.6
      PYTHON_BUILD: ''
    - PYTHON_VERSION: 3.6
      PYTHON_BUILD: '-x64'
    - PYTHON_VERSION: 3.7
      PYTHON_BUILD: ''
    - PYTHON_VERSION: 3.7
      PYTHON_BUILD: '-x64'
    - PYTHON_VERSION: 3.8
      PYTHON_BUILD: ''
    - PYTHON_VERSION: 3.8
      PYTHON_BUILD: '-x64'

matrix:
  exclude:
    - platform: x86
      PYTHON_BUILD: '-x64'
    - image: Ubuntu
      platform: x86
      PYTHON_BUILD: ''
    - image: macOS
      platform: x86
      PYTHON_BUILD: ''

stack: python %PYTHON_VERSION%

build: off

test_script:
  # Windows. Both 32 and 64 bit Python versions
  - cmd: set PYTHON_PATH=C:\PYTHON%PYTHON_VERSION:.=%%PYTHON_BUILD%
  - cmd: set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%OLDPATH%
  - cmd: python -VV
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -m pip install .[test]
  - cmd: python -m pytest

  # Linux and Mac
  - sh: python -VV
  - sh: python -c "import struct; print(struct.calcsize('P') * 8)"
  - sh: pip install .[test]
  - sh: PATH=/home/appveyor/.local/bin:${PATH}
  - sh: pytest
